version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: app-user
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: app-user
          POSTGRES_DB: grety_test
    working_directory: ~/repo
    steps:
      - checkout
      - bundle install --jobs=4 --retry=3 --path vendor/bundle
      - bundle exec rake db:create
      - bundle exec rake db:schema:load
      - bundle exec rake spec